### ISSUE TITLE
Exclude certain payment types from revenue widget

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#105]
Exclude:

- Credit note
- Credit note redeemed
- Agent credit
- unspecified payment

**Comment by anthonygoslar** [comment]
Should 'unspecified' not be in there. It could be changed to 'Other'.

**Comment by simonbharrison1** [comment]
We usually use unspecified for tidying up. Any 'real' payments should go in one of the other categories.



-------- Original message --------

**Comment by anthonygoslar** [comment]
Okay. I'll remove it and make a note in the description for other users.

**Comment by simonbharrison1** [comment]
Re-opened as discussed (was applied to graph not widget)
