### ISSUE TITLE
On management dash graphs, tool tips show the Friday of the week the bar refers to - can we change to the Monday?

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#106]

**Comment by anthonygoslar** [comment]
They run the query by the day the week ended on. Are you asking for it to be the week start on? For instance, if it ends on Friday 2021-02-05, should it state Monday 2021-01- 27 or Monday 2021-02-06? 

The knock-on effect is the way I tally up the monthly data: I add up all the Friday's with a month that matches that month. Using the example above, I add up all the Friday's which have the month '02' in them to get the data for February. If I change the labels, there's a chance of the monthly and weekly data not matching up where the Friday and Monday aren't in the same month.

**Comment by simonbharrison1** [comment]
Ok lets leave it as is - it's just a minor thing.
