### ISSUE TITLE
Issue with Constance config settings & visa not required student setting

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#107]
I am working on ZDAV36468 and want to move her from completed to current, so I can then abandon.  Have unticked visa required in the boss, but m getting error below.

![image](https://user-images.githubusercontent.com/77050948/110216275-e8cf9d00-7eb6-11eb-92b7-8173b4d06a2b.png)

Also tried temporarily disabling in constance config, but same result

**Comment by anthonygoslar** [comment]
This has been fixed from the global settings changes under config. In addition to this, I've added two new fields to each student's form. 
![image](https://user-images.githubusercontent.com/30745006/110233323-ebb8a500-7f2b-11eb-9a9e-c3516b570576.png)

By Default these are set to True (i.e. boxes are ticked). They can only be seen by a superuser though. So only a superuser will have the option to change the settings from the frontend forms as the option will only be given to them.
