### ISSUE TITLE
Change active students widget to weekly

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#108]
Active students widget to shown number of 'bums on seats' for current week + last/next week (last week inc completed, next week inc confirmed)

**Comment by anthonygoslar** [comment]
Completed. To be checked on dev server.

**Comment by simonbharrison1** [comment]
It’s a bit tricky to check on the dev server with the old data actually.  When are we next planning to pull in the live data?

I can see that the labels on the widget still say the months so that will need to be changed.

**Comment by anthonygoslar** [comment]
I needed a chance to push the most recent results to the dev server.
They're up now.
