### ISSUE TITLE
Add 'City' field to agent profile

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#109]
Johannes requested this - I think it's mainly for Brazil (it's a big country!)

**Comment by anthonygoslar** [comment]
Yes I'll add it. I have it on my list and it shouldn't take too long. I
need to find a list of all the cities in the countries, and then filter
them based on the country selection.

**Comment by anthonygoslar** [comment]
Rolled out in 0.6.0.2
