### ISSUE TITLE
Transfer not showing in accommodation/list/ + not showing on S profile in testing

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#110]
- Student with transfer on S profile page but transfer not showing in list (eg WMEZ37351)
- Actually there are no transfers at all showing in the list
- When I added a transfer to TMCT32874 it didn't how on profile page or in the list

**Comment by anthonygoslar** [comment]
It now has a transfer type. This was done a bit back when I was asked to change it to a selection allowing for "One way" and "Return". 

- On the accommodation list, it's the last column. 
- On the profile page, its now in a column next to the date for the accomodation
