### ISSUE TITLE
In the grey quick nav drop down, 'bookings' links to finances/payments/list/

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#111]
change link to finances/course_booking/list

**Comment by anthonygoslar** [comment]
Corrected.

**Comment by simonbharrison1** [comment]
Hey Gos, still seems to be pointing to finances/payments/list On dev and live…

**Comment by anthonygoslar** [comment]
It’ll be updated with the next rollout. I don’t want to push to the live
server too often while users are using it.
