### ISSUE TITLE
Session times -2 hrs on PRINT CLASS LISTS

### ISSUE THREAD

**Issue by Mon1elc** [anthonygoslar/LMS-Support#116]
They show as 2 hrs earlier .
Registers also.

**Comment by Mon1elc** [comment]
This is pretty urgent, as we have to amend manually by hand on the notice boards , thanks

**Comment by anthonygoslar** [comment]
This has been addressed and will be deployed with 0.6.0.1

**Comment by Mon1elc** [comment]
Hi Anthony, is there no way we can change it , apart from me scratching it out manually on the displayed printed sheets ?
***@***.***D7270F.B1C96EC0]


thanks
Monica

**Comment by anthonygoslar** [comment]
I’ve already corrected it. It’ll be rolled out this weekend.

**Comment by anthonygoslar** [comment]
This update has been rolled out. Please reopen this if it's not showing the correct timezone.
