### ISSUE TITLE
Change accommodation 1-11 weeks / 12+ weeks threshold

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#117]
Type | Current | New
-- | -- | --
1-11 weeks (all accom) | <= 86 days | <= 83 days
12+ weeks (all accom) | >= 87 days | >= 84 days

This is to bring in line with Symfony.  Fairly urgent as there could be discrepancies between the prices on the 2 systems.  Applies to all the accom options.

**Comment by simonbharrison1** [comment]
Hey Gos, please can we prioritize this issue?

**Comment by anthonygoslar** [comment]
Sure. I'll look at it this morning.

**Comment by simonbharrison1** [comment]
Thanks, Symfony seems to have it at >= 78 days for some reason so I need to sort that out too.  I’ll copy you in…

**Comment by simonbharrison1** [comment]
Hmm, I'm trying to decide exactly what the threshold should be, maybe it should be 81 days.  Let me get back to you this morning on this.

**Comment by simonbharrison1** [comment]
Ok, I've worked it out.  Day 77 is last day of 11 weeks, so day 78 is the beginning of the 12th week.  So...

Type | Current | New
-- | -- | --
1-11 weeks (all accom) | <= 77 days | <= 83 days
12+ weeks (all accom) | >= 78 days | >= 84 days

Thanks!

**Comment by anthonygoslar** [comment]
I current have this and will make the change as follows:

Type | Current | New
-- | -- | --
1-11 weeks (all accom) | <= 86 days | <= 83 days
12+ weeks (all accom) | > 86 days | > 83 days

**Comment by anthonygoslar** [comment]
Changed to 77
