### ISSUE TITLE
Error occurs when submitting bulk attendances

### ISSUE THREAD

**Issue by Mon1elc** [anthonygoslar/LMS-Support#119]
![image](https://user-images.githubusercontent.com/76612584/111783980-823d7c80-88c3-11eb-9df1-74617889651a.png)

**Comment by Mon1elc** [comment]
Hi, This issue persists. there is quite a back-log that I need to update, for new teachers who couldn't sign in . 
Thanks

**Comment by anthonygoslar** [comment]
Fixed and tested on live server.
