### ISSUE TITLE
City selector on +Agent not working on dev

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#120]
Just says no results found
![image](https://user-images.githubusercontent.com/77050948/112109300-0d678c80-8bba-11eb-9ac8-ef2758e53e1a.png)

**Comment by anthonygoslar** [comment]
It’s currently initiated for Agents only. Could you try a hard refresh?

**Comment by simonbharrison1** [comment]
Still the same after hard refresh...

**Comment by anthonygoslar** [comment]
Okay thanks. I’ll take a look and see what’s up. I tested on Sunday after
deployment and it was working then.

**Comment by simonbharrison1** [comment]
Seems to be working now :)
