### ISSUE TITLE
Layout/formatting of ALLOCATE students page

### ISSUE THREAD

**Issue by Mon1elc** [anthonygoslar/LMS-Support#121]
![image](https://user-images.githubusercontent.com/76612584/112119299-eb740700-8bc5-11eb-910e-8e4e752842f8.png)

It used to be a lot easier to view when we could see ALL the levels of that session, now we can only see Beginner and some of the Elem levels. 
When dragging a student name, we have to navigate down by selecting name and using keyboard arrows, as the page doesn't scroll down automatically when we lower the student name. Any chance we could revert to the horizontal layout of classes (levels) and not the larger portrait view? 

NOT URGENT, just an enhancement :)

**Comment by anthonygoslar** [comment]
I've added collapsible arrows to the classes to assist with this. Does this help?

**Comment by Mon1elc** [comment]
Hi, Ok I noticed this now, thank you!
