### ISSUE TITLE
Urgent - USER:  Nervina Pillay-Ellis cannot view classes allocated to her 

### ISSUE THREAD

**Issue by Mon1elc** [anthonygoslar/LMS-Support#122]
![image](https://user-images.githubusercontent.com/76612584/112139750-d86c3180-8bdb-11eb-8642-cffb637191c8.png)

![image](https://user-images.githubusercontent.com/76612584/112139808-e7eb7a80-8bdb-11eb-8474-7cb22ac15d96.png)

Nervina has been loaded as a teacher and a user, she can sign in - see attached, But she cannot access her classes allocated to her. T/Th Elective , and last 2 weeks of classes as well.

**Comment by anthonygoslar** [comment]
She should be able to view them now. We needed to add her user to the Teacher. I realize that this should be done automatically, so I'll open a ticket for this.

**Comment by Mon1elc** [comment]
Hi Anthony,
Thanks !
________________________________
