### ISSUE TITLE
CREATE class for Monday 5th March 

### ISSUE THREAD

**Issue by Mon1elc** [anthonygoslar/LMS-Support#125]
I need to create a unique class :  see screenshot.  It's in the GE_Morn session but just a different name (EAP) it will be Upper Int level but I need to call it EAP as I'm customizing a class for some students. 
Is this possible please?

It wouldn't let me do it. 
![image](https://user-images.githubusercontent.com/76612584/112949801-e8cf5f80-9139-11eb-8544-0a1002b7b4b4.png)

**Comment by Mon1elc** [comment]
Actually, never mind - I just changed the name of Morn_Upper Int 2 as follows: 
(this will suffice)
![image](https://user-images.githubusercontent.com/76612584/112950256-6004f380-913a-11eb-8218-72de50ae9e68.png)

**Comment by anthonygoslar** [comment]
Is EAP a different level? If so we can add it as a separate level or we can add another class (such as class 3).

**Comment by Mon1elc** [comment]
I’ve done this as suggested, called an “Upper 3” class EAP instead of making a new level.
Thanks , can close this issue.
