### ISSUE TITLE
Booking type NOT evident on Sessions page

### ISSUE THREAD

**Issue by Mon1elc** [anthonygoslar/LMS-Support#126]
Hi, 
On this page I cannot see if they're ONLINE or not, so I cannot allocate sessions unless I go into their name to view what product is booked. (or I can see it on Manage Bookings stream but then I must make a mental note for myself when I go to Sessions view)
![image](https://user-images.githubusercontent.com/76612584/113127582-3373d900-9219-11eb-911d-b07f36dc4d89.png)

**Comment by anthonygoslar** [comment]
The next item I have on my list is to remove BOOKING TYPE so that it can be collapsed into COURSE TYPE. I'll try speed this up to solve this issue. If this doesn't work then we better check with Christelle.
