### ISSUE TITLE
Abandoned courses -  students still appear to be allocated for sessions

### ISSUE THREAD

**Issue by Mon1elc** [anthonygoslar/LMS-Support#132]
![image](https://user-images.githubusercontent.com/76612584/113741611-1c922280-9702-11eb-9f9d-704ae5418723.png)

I assign sessions when bookings are CONFIRMED. 
Later when admin changes status to ABANDONED , I still see the names to be allocated to class, which I may accidentally do, unless I've been told that the course is abandoned. 
Is there any way that they can disappear from 'allocate to class' when course status reads abandoned?
Now I have to go into their profile and delete sessions. 
Thanks

**Comment by anthonygoslar** [comment]
Hi Monica

Good point. I've add this to the next roll out that we remove sessions for abandoned courses.

**Comment by anthonygoslar** [comment]
Are any CONFIRMED courses allocated sessions?

**Comment by Mon1elc** [comment]
Hi Anthony,
I always allocate sessions to CONFIRMED status students, so that I can look at the week  ahead and visualise numbers per level/class on the ASSIGN STUDENT to CLASS page.
Then sometimes admin will change the status to abandoned but the student remains to be assigned to class. I don’t know until I investigate and open their profile.
Does this answer your question appropriately?

Thanks
Monica

**Comment by anthonygoslar** [comment]
Yes it does, thanks.

**Comment by anthonygoslar** [comment]
Hi Monica

Please check if its still doing so. I've dropped abandoned bookings from the database query sets for attendances so they shouldn't show up anymore. If the bookings are restored, they'll reappear, however they will be deleted if they're still abandoned after the booking end date.
