### ISSUE TITLE
Visas and ID's not required

### ISSUE THREAD

**Issue by 01450900** [anthonygoslar/LMS-Support#138]
Hello,
I reviewed the ID & Visas Tb today on the Admin Dashboard. 
There are A LOT of students that have NO for 'Required?'.  I know that SA students are excluded, and I know that I might have overriden a few but it still seems like a lot. I'm going to slowly start making them YEs required but is there something I'm missing?
Attached shows a snapshot at 12:45pm today 
[Visas Not Required.xlsx](https://github.com/anthonygoslar/LMS-Support/files/6426527/Visas.Not.Required.xlsx)

**Comment by anthonygoslar** [comment]
I jumped on now and saw that there are four students with 'NO' for a visa
requirement who aren't South African, three students for 'NO' for id
requirements who aren't South African. Currently, South African's and TEFL
courses are overwritten for Visa and ID requirements in the settings but
you can change this.

The columns of the table are a little confusing in reading this. I may add
some colour to make them distinct. Also, does this table need a country
column?

Should we go through it to ensure that it's correct and that you know how
it works?

**Comment by 01450900** [comment]
I’ve sent you a meeting request

Morning!
