### ISSUE TITLE
Copying the reg code

### ISSUE THREAD

**Issue by 01450900** [anthonygoslar/LMS-Support#139]
It's such a tiny thing - I'd like that when I copy the reg code it doesn't pick up all the background and bold etc. It's quite a few extra touches to get it looking normal again.
![reg code](https://user-images.githubusercontent.com/77271198/117138499-632f7700-adab-11eb-8a6d-f648f8533ed1.JPG)

**Comment by anthonygoslar** [comment]
I've pushed a fix to the live server. Please re-open the issue if it doesn't work.

**Comment by 01450900** [comment]
YALS36892
This makes me happy – thank you!
