### ISSUE TITLE
REcognising Duplicates

### ISSUE THREAD

**Issue by 01450900** [anthonygoslar/LMS-Support#141]
Duplicates - I don't think the system is recogninsing the same  names in upper and lower case as duplicates.
EG TNTO35320
![Tang](https://user-images.githubusercontent.com/77271198/117286594-ac460080-ae69-11eb-93d9-040667cb04a6.JPG)
I'm not going to delete this one until you advise but I have marked one clearly as DO NOT USE

**Comment by anthonygoslar** [comment]
Duplicates has been changed to email addresses on the dev server. This should be a better way of identifying unique students.
