### ISSUE TITLE
Visas required or not

### ISSUE THREAD

**Issue by 01450900** [anthonygoslar/LMS-Support#144]
Hi
This is just a marker. I keep coming across students which should have both ID and Visa marked as required but they don't.  CAth says she isn't changing them. I'm not.   
JGOM31308 - so I've not changed this one.
Could you have a look please?
Thanks
Christelle

**Comment by anthonygoslar** [comment]
I'll look into it and revert back to you.

**Comment by anthonygoslar** [comment]
I found a problem on the create a new student form causing the default value to be False for these fields when a non-superuser added a student. I have implemented a fix and tested it by creating a temporary student.
