### ISSUE TITLE
Notes on Orange Agent payout ledger entries

### ISSUE THREAD

**Issue by 01450900** [anthonygoslar/LMS-Support#28]
Looks like the notes only showing on payments (grey button) and not agent payout/debit (orange button). Eg:

I'm unable to add a screenshot. eg NSHA37055 See email 8 Jan 3:33pm 

Thanks
Christelle

**Comment by anthonygoslar** [comment]
You can copy and image and paste it into this box. It'll upload the image and add a link.

Is the note not the text underneath written in italics. I've highlighted it in yellow below.

![image](https://user-images.githubusercontent.com/30745006/105839262-e5a0e180-5fd9-11eb-9e11-3ce1dfc87166.png)
