### ISSUE TITLE
https://www.uctlanguagecentre.online/dashboard/

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#42]
On https://www.uctlanguagecentre.online/dashboard/ - which is my default post login landing page - it's the student admin dashboard but only shows the Incoming students table.  When I go to it from the menu I get both tables

And the tab where this is is called Sessions for some reason - change label to booking status.

**Comment by anthonygoslar** [comment]
This is Monica's dash and is the Course Admin dash. The other is the Student Admin dash.
