### ISSUE TITLE
Split booking window

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#44]
- Remove copy at top
- remove fields: Booking code, source, agent
- remove field booked date (use modified on for new split booking)
- remove custom course tickboxes
- show lock/unlocked padlock (but show/view only)

We can improve on this longer term but the above changes will just neaten it up for now.

**Comment by anthonygoslar** [comment]
I agree that it needs a rehash. I've considered doing it differently:
1. Pop up a modal asking if you want to simply add a break, or also change
project details; and if you want to keep the finances as is or if you'd
like to update them automatically;
2. Based on this feedback, bring back different forms with the details
needed.
3. The form will have a "break start date", and a "break end date". The
system will then split the course and change the dates accordingly.

Regards
Anthony Goslar
+27 82 928 0621

**Comment by anthonygoslar** [comment]
- [x] Remove copy at top
- [x] remove fields: Booking code, source, agent
- [X ] remove field booked date (use modified on for new split booking)
- [x] remove custom course tickboxes
- [x] show lock/unlocked padlock (but show/view only)
