### ISSUE TITLE
No info showing on Booking Tab: MMEN37781

### ISSUE THREAD

**Issue by 01450900** [anthonygoslar/LMS-Support#50]
![image](https://user-images.githubusercontent.com/77271198/104996387-7acb3580-5a30-11eb-8981-547795f4a808.png)
![MMEN37781](https://user-images.githubusercontent.com/77271198/104996497-a2220280-5a30-11eb-950a-18893fc543ee.JPG)

**Comment by anthonygoslar** [comment]
I'm getting the information coming up. When you click on the tabs does it do anything?

![image](https://user-images.githubusercontent.com/30745006/105015445-3fd5fb80-5a4a-11eb-9c12-057aa7e77ba2.png)
