### ISSUE TITLE
Documents upload required field - URGENT

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#52]
So we need to somehow force Admin to upload the visa and passport docs and include the issue and expiry date.  I'm not exactly sure how, but this is really quite an urgent one, so let's discuss today if poss.

**Comment by anthonygoslar** [comment]
Alright. This is a nudge feature so let's see the best way to achieve it.

**Comment by anthonygoslar** [comment]
This feature has been added and will be tested on the dev server.
