### ISSUE TITLE
Add Specials to Product list 

### ISSUE THREAD

**Issue by 01450900** [anthonygoslar/LMS-Support#54]
Last year we sat in DH and discussed Specials.  We need to be able to show that an item is a special.  At the moment, we are just using custom.  So in the discount category with Discretionary, REgional and Launch, can we please add Special?

**Comment by anthonygoslar** [comment]
Could you send me a list of the specials with their prices?

**Comment by 01450900** [comment]
Hello,

Can we talk about this tomorrow, please?  I think we decided not to have specific detailed specials, rather just a generic product that we could show that a special was being used.

I’ve attached the current specials – but the point is they will change.

Cheers
Christelle

**Comment by 01450900** [comment]
Gosh had completely forgotten about that.  Yes we can discuss tomorrow.

From: Christelle Van Niekerk <christelle.vanniekerk@uct.ac.za>
Sent: Thursday, 11 February 2021 11:46
To: anthonygoslar/LMS-Support <reply@reply.github.com>
Cc: Simon Harrison <simon.harrison@uct.ac.za>
Subject: RE: [anthonygoslar/LMS-Support] Add Specials to Product list (#54)

Hello,

Can we talk about this tomorrow, please?  I think we decided not to have specific detailed specials, rather just a generic product that we could show that a special was being used.

I’ve attached the current specials – but the point is they will change.

Cheers
Christelle

**Comment by anthonygoslar** [comment]
I recall this issue being closed. Please reopen it if this is not the case.
