### ISSUE TITLE
Alex Abdellah cannot update his registers GE Morn_Adv_c 1

### ISSUE THREAD

**Issue by Mon1elc** [anthonygoslar/LMS-Support#55]
he can view it but when he enters scores and submits it throws an error message . This only happens with GE_Morn, not his Conv_Adv_c1

**Comment by Mon1elc** [comment]
This is quite urgent, thanks, as I have to do all his registers for him

**Comment by Mon1elc** [comment]
As a manager usre, Alex also cannot see any completed registers submitted by any other teacher, they all appear 'missing' . Please check this also while working on this error , thanks

**Comment by anthonygoslar** [comment]
He'll have to login as a manager and not a teacher. Is this still an issue?

**Comment by Mon1elc** [comment]
I think this is resolved, it was his teacher log in that was throwing the errors.
