### ISSUE TITLE
Preventing further action without passport doc / visa doc / Passport number

### ISSUE THREAD

**Issue by 01450900** [anthonygoslar/LMS-Support#59]
Hello Anthony,

Can we discuss please?  We need to put something in place on the LMS, at a certain to be decided point,  that will prevent a student from being able to be in the school without the visa and passport docs being uploaded. 

We need to be able to capture bookings wihtout that info, and Monica needs to be able to assign them to class before they arrive. The goal is: we need to ensure that the student has a valid via and passport and that these documents are uploaded to the LMS.  In the first week of their visit. 
Maybe the cut off point could be when we convert the status from Confirmed to Current? 

I think maybe me, you and Simon need to chat. 

I'd say this is fairly urgent. 
thanks
Christelle

**Comment by anthonygoslar** [comment]
Hi Christelle

I've chatted with Simon about this. I agree the point at which a confirmed
booking becomes current is the best place. It would also like up with the
businesses procedures of processing incoming students.

I can add a validator that checks for these items, and if false, prevents
updating with an error message that the documents must be uploaded. We can
then add an override to this which a superuser can change to allow for
special circumstances. It may also be necessary to allow for certain
nationalities to be allowed such as South African students.

I've opened a ticket already for this.

Kind Regards
Anthony Goslar
