### ISSUE TITLE
Activate classes order classes not working

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#61]
Just hanging on save changes.  Dev and live

**Comment by simonbharrison1** [comment]
Also not working from 'Update Lecture' form

**Comment by Mon1elc** [comment]
Could we possibly move this up the priority list , please?

**Comment by anthonygoslar** [comment]
Sure. I'll try fix it tomorrow.

Kind Regards
Anthony Goslar
Mobile & WhatsApp: +27 82 928 0621
(Sent from my mobile device)

**Comment by anthonygoslar** [comment]
I've made some changes to speed it up and pushed these to the live server. Please re-open the issue if its not working properly.

**Comment by Mon1elc** [comment]
I’ll check!
Thanks, it’s my last few days in my current post, so I’m handing over a lot!
