### ISSUE TITLE
link in all finance documents - fairly urgent

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#69]
Ag - because we forgot to change it when we went on to the new booking system.  It's the link here:

![image](https://user-images.githubusercontent.com/77050948/106293290-826fb300-6256-11eb-9581-8073b30cc457.png)

please change to https://app.uctlanguagecentre.com/ in the 4 finance docs

Thanks.

**Comment by anthonygoslar** [comment]
Changed in 3x templates and tested on the invoicing template.

**Comment by simonbharrison1** [comment]
Please also add to let_finances_invoice_agent.

And please will you add the whole payment instructions section (with the updated link) to let_finances_agent_statement

Thanks

**Comment by anthonygoslar** [comment]
Done.
