### ISSUE TITLE
On record daily attendance window, date/time seems to be UTC

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#77]
![image](https://user-images.githubusercontent.com/77050948/107607656-80d4c080-6c42-11eb-9928-7ae0deda05de.png)

**Comment by anthonygoslar** [comment]
I'm getting the correct time. Is it the same view under /events/events_attendance/?

![image](https://user-images.githubusercontent.com/30745006/109468964-0f847280-7a76-11eb-8ddd-c572c09f5c74.png)

**Comment by anthonygoslar** [comment]
This has been addressed and will be deployed with beta 0.6.0.1
