### ISSUE TITLE
Some attendance not showing in Student attendance list

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#86]
But they do seem to have an attendance on the S profile
![image](https://user-images.githubusercontent.com/77050948/107765655-e5734680-6d3a-11eb-90f7-e61d3689862f.png)

**Comment by anthonygoslar** [comment]
This is pulling attendance based on courses. I can pull them for the 
student as a whole.

**Comment by anthonygoslar** [comment]
This is pulling attendance based on courses. I can pull them for the student as a whole.
![image](https://user-images.githubusercontent.com/30745006/107772032-5408d200-6d44-11eb-9e76-bc21befe39c9.png)

**Comment by simonbharrison1** [comment]
Yes, we need to keep the course filter but the key thing is the student attendance.  Suggest we have both in the list.  Let's change the page heading to just "attendance"

**Comment by simonbharrison1** [comment]
Sorry I mean the booking status filter because that is how we search for CURRENT

**Comment by simonbharrison1** [comment]
And the column headings to Student Attendance and Booking attendance.

**Comment by anthonygoslar** [comment]
We can do that. I'll update it accordingly.

**Comment by anthonygoslar** [comment]
Updated. It'll be pushed out with the next beta as it relies on calculations which aren't currently available on the live server.
