### ISSUE TITLE
Show/Hide classes not feeding through 

### ISSUE THREAD

**Issue by Mon1elc** [anthonygoslar/LMS-Support#92]
Tried to hide/deactivate a number of classes but they still show up on: assign room or teacher page. 
Need to clear these please.

**Comment by anthonygoslar** [comment]
After the recent change fixing issue #61, I tested this on the assign room and teacher page and they were working. Please reopen the issue is this is not the case for you.

**Comment by Mon1elc** [comment]
This seems to be working fine now , thanks !
@Alex FYI:  it was the show/hide classes function.
