### ISSUE TITLE
Error on loading lists from Administrator dash

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#95]
Error appearing when trying to load 'Next Monday' and 'Following Friday'

![image](https://user-images.githubusercontent.com/77050948/109644181-d45d6e80-7b5d-11eb-8262-0fa4d228aeb0.png)

**Comment by anthonygoslar** [comment]
Some records don't have uploaded documents. Logic has been added to deal with this case.

**Comment by simonbharrison1** [comment]
Morning!  Issue persists in the live version.

**Comment by anthonygoslar** [comment]
Fixed and checked.
